export enum ExecutorsMutationTypes {
    SET_EXECUTORS = 'SET_EXECUTORS',
    SET_EXECUTOR = 'SET_EXECUTOR',
    SET_EXECUTORS_ERROR = 'SET_EXECUTORS_ERROR',
    SET_EXECUTORS_COUNT = 'SET_EXECUTORS_COUNT',
    CHANGE_EXECUTORS_PAGE = 'CHANGE_EXECUTORS_PAGE',
    CHANGE_EXECUTORS_LOADING = 'CHANGE_EXECUTORS_LOADING',
}