export enum CustomersMutationTypes {
    SET_CUSTOMERS = 'SET_CUSTOMERS',
    SET_CUSTOMER = 'SET_CUSTOMER',
    SET_CUSTOMERS_ERROR = 'SET_CUSTOMERS_ERROR',
    SET_CUSTOMERS_COUNT = 'SET_CUSTOMERS_COUNT',
    CHANGE_CUSTOMERS_PAGE = 'CHANGE_CUSTOMERS_PAGE',
    CHANGE_CUSTOMERS_LOADING = 'CHANGE_CUSTOMERS_LOADING',
    SET_CUSTOMERS_SEARCH_STRING = 'SET_CUSTOMERS_SEARCH_STRING',
}