export enum ProgramsMutationTypes {
    SET_PROGRAMS = 'SET_PROGRAMS',
    SET_PROGRAM = 'SET_PROGRAM',
    SET_PROGRAMS_ERROR = 'SET_PROGRAMS_ERROR',
    SET_PROGRAMS_COUNT = 'SET_PROGRAMS_COUNT',
    CHANGE_PROGRAMS_PAGE = 'CHANGE_PROGRAMS_PAGE',
    CHANGE_PROGRAMS_LOADING = 'CHANGE_PROGRAMS_LOADING',
}